[package]
name = "solana-address"
description = "Solana account addresses"
documentation = "https://docs.rs/solana-address"
version = "1.1.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.cargo-semver-checks.lints]
# cargo-semver-checks performs checks on the exported symbol graph, so re-exports
# are considered different elements and they will be flagged as breaking changes
# even if the public API is equivalent.
declarative_macro_missing = "allow"
enum_missing = "allow"
function_missing = "allow"
module_missing = "allow"
pub_module_level_const_missing = "allow"
struct_missing = "allow"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
atomic = ["solana-address-v2/atomic"]
borsh = ["solana-address-v2/borsh", "alloc"]
bytemuck = ["solana-address-v2/bytemuck"]
curve25519 = ["solana-address-v2/curve25519", "sha2", "syscalls"]
decode = ["solana-address-v2/decode", "error"]
dev-context-only-utils = ["solana-address-v2/dev-context-only-utils", "rand"]
error = ["solana-address-v2/error"]
frozen-abi = ["solana-address-v2/frozen-abi", "std"]
rand = ["solana-address-v2/rand", "atomic", "std"]
sanitize = ["solana-address-v2/sanitize"]
serde = ["solana-address-v2/serde"]
sha2 = ["solana-address-v2/sha2", "error"]
std = ["solana-address-v2/std", "decode", "alloc"]
alloc = ["solana-address-v2/alloc"]
syscalls = ["solana-address-v2/syscalls", "error"]

[dependencies]
solana-address-v2 = { package = "solana-address", version = "2.0", features = ["copy"] }

[lints]
workspace = true
